#!/usr/bin/env python3
import subprocess

subprocess.run(["date"])
print('-------------')
print('Use print command to show to return of subprocess object with exit status or return code 0 success')
print(subprocess.run(["date"]))
print('-------------')
print('Let python launch subprocess to wait for 3 seconds, python will wait 3 seconds for the subprocess to complete')
print(subprocess.run(["sleep","3"]))
print('-------------')
print('If the subprocess fail with return code != 0, python can capture this info')
exitstatus = subprocess.run(["ls","on_none_existing_file"])
print(exitstatus)
print("Result return code: {}".format(exitstatus.returncode))
print('-------------')
print('We can capture STDOUT and STDERR for further processing')
print('Here host is successful command')
result = subprocess.run(["host","8.8.8.8"], capture_output=True)
print(result)
print(result.returncode)
print(result.stdout)
print(result.stdout.decode().split())
print(result.stderr)
print('-------------')
print('Here rm on a non existing file will erre')
result = subprocess.run(["rm","non-existing-file"], capture_output=True)
print(result)
print(result.returncode)
print(result.stdout)
print(result.stderr)
print(result.stderr.decode().split())
print('--------------')
print('We will add to the PATH an additional directory')
import os
import subprocess
my_env = os.environ.copy()
print(my_env)
subprocess.run(["clear"])
print(my_env["PATH"])
my_env["PATH"] = os.pathsep.join(["/Users/herveyu/Desktop/hyu/py/pywithos/",my_env["PATH"]])
result = subprocess.run(["try_os.py"],env=my_env)
print(my_env["PATH"])
